---
swagger: "2.0"
info:
  version: "0.0.3"
  title: "Customer Portal API"
paths:
  /chargeOfSales:
    get:
      description: "担当営業情報を提供する"
      operationId: "chargeOfSalesGET"
      parameters:
      - name: "id"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID（会社IDと同値？）"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
  /company:
    get:
      description: "会社情報を提供"
      operationId: "companyGET"
      parameters:
      - name: "id"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_1"
      x-swagger-router-controller: "Default"
  /companyList:
    get:
      description: "担当する顧客会社名リストを提供"
      operationId: "companyListGET"
      parameters:
      - name: "email"
        in: "query"
        description: "リクエスター（NetOne担当者）のEmailアドレス"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Default"
  /customer:
    get:
      description: "顧客情報を提供"
      operationId: "customerGET"
      parameters:
      - name: "email"
        in: "query"
        description: "顧客のEmailアドレスを検索キーとして設定"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/inline_response_200_3"
      x-swagger-router-controller: "Default"
  /mContract:
    get:
      description: "保守契約情報を提供"
      operationId: "mContractGET"
      parameters:
      - name: "id"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      - name: "contract"
        in: "query"
        description: "個別契約番号"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_4"
      x-swagger-router-controller: "Default"
  /mContractList:
    get:
      description: "保守契約リスト情報を提供"
      operationId: "mContractListGET"
      parameters:
      - name: "id"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      - name: "contract"
        in: "query"
        description: "個別契約番号"
        required: false
        type: "string"
      - name: "serial"
        in: "query"
        description: "シリアル番号"
        required: false
        type: "string"
      - name: "contractor"
        in: "query"
        description: "契約先名称"
        required: false
        type: "string"
      - name: "customerContractNo"
        in: "query"
        description: "顧客契約番号"
        required: false
        type: "string"
      - name: "enduser"
        in: "query"
        description: "エンドユーザー"
        required: false
        type: "string"
      - name: "startdate"
        in: "query"
        description: "契約開始日"
        required: false
        type: "string"
      - name: "enddate"
        in: "query"
        description: "契約終了日"
        required: false
        type: "string"
      - name: "index"
        in: "query"
        description: "保守契約一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
      - name: "max"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は50最大値は500）"
        required: false
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_5"
      x-swagger-router-controller: "Default"
  /product:
    get:
      description: "製品詳細情報を提供"
      operationId: "productGET"
      parameters:
      - name: "productid"
        in: "query"
        description: "製品ID（productListで取得した一覧から選択した製品ID）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_6"
      x-swagger-router-controller: "Default"
  /productList:
    get:
      description: "保守契約済み製品リスト情報を提供"
      operationId: "productListGET"
      parameters:
      - name: "id"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: true
        type: "string"
      - name: "customerid"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      - name: "contract"
        in: "query"
        description: "個別契約番号"
        required: false
        type: "string"
      - name: "serial"
        in: "query"
        description: "シリアル番号"
        required: false
        type: "string"
      - name: "startdate"
        in: "query"
        description: "契約開始日"
        required: false
        type: "string"
      - name: "enddate"
        in: "query"
        description: "契約終了日"
        required: false
        type: "string"
      - name: "productid"
        in: "query"
        description: "製品ID"
        required: false
        type: "string"
      - name: "productname"
        in: "query"
        description: "製品テキスト"
        required: false
        type: "string"
      - name: "index"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
      - name: "max"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は50最大値は500）"
        required: false
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_7"
      x-swagger-router-controller: "Default"
definitions:
  inline_response_200_5:
    required:
    - "id"
    - "numof"
    - "total"
    properties:
      total:
        type: "integer"
        description: "検索条件に一致した件数"
      index:
        type: "integer"
        description: "データの開始位置"
      numof:
        type: "integer"
        description: "データの提供数"
      id:
        type: "string"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先ID、納入先コード等で使用しているIDを想定）Inputさ\
          れたidと同じ値となる"
      Contracts:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_5_Contracts"
  inline_response_200_6:
    required:
    - "contract"
    - "productid"
    properties:
      eol:
        type: "boolean"
        description: "EOL"
      productid:
        type: "string"
        description: "製品ID"
      dedicatedmaintenanceno:
        type: "string"
        description: "専用保守部材管理番号"
      contract:
        type: "string"
        description: "個別契約番号"
      eos:
        type: "boolean"
        description: "EOS"
      sla:
        type: "string"
        description: "SLA"
      modelno:
        type: "string"
        description: "メーカー型番"
      servicetypecode:
        type: "string"
        description: "サービス種別コード"
      moniteringtype:
        type: "string"
        description: "モニタリング種別"
      startdate:
        type: "string"
        description: "保守開始日"
      servicemenu:
        type: "string"
        description: "メニュー名"
      qa:
        type: "boolean"
        description: "QA有無"
      servicetype:
        type: "string"
        description: "サービス種別"
      enddate:
        type: "string"
        description: "保守終了日"
      accountmgmtno:
        type: "string"
        description: "アカウント管理番号"
      shippingno:
        type: "string"
        description: "出荷番号"
      serial:
        type: "string"
        description: "シリアル番号"
      productname:
        type: "string"
        description: "製品テキスト"
      shippingdate:
        type: "string"
        description: "出荷日時"
      individualcontract:
        type: "string"
        description: "製品／個別条件書"
      servicemodelno:
        type: "string"
        description: "サービス型番"
      productlistprice:
        type: "string"
        description: "製品定価"
  inline_response_200_5_Contracts:
    required:
    - "contract"
    - "subject"
    properties:
      chargeofenginner:
        type: "string"
        description: "担当技術"
      enddate:
        type: "string"
        description: "契約終了日"
      enduser:
        type: "string"
        description: "エンドユーザー"
      subject:
        type: "string"
        description: "契約名称"
      contract:
        type: "string"
        description: "個別契約番号"
      chargeofsales:
        type: "string"
        description: "担当営業"
      customercontractno:
        type: "string"
        description: "顧客契約番号"
      startdate:
        type: "string"
        description: "契約開始日"
  inline_response_200_7:
    required:
    - "id"
    - "numof"
    - "total"
    properties:
      total:
        type: "integer"
        description: "検索条件に一致した件数"
      index:
        type: "integer"
        description: "データの開始位置"
      numof:
        type: "integer"
        description: "データの提供数"
      Product:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_7_Product"
      id:
        type: "string"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先ID、納入先コード等で使用しているIDを想定）Inputさ\
          れたidと同じ値となる"
  inline_response_200_1:
    required:
    - "id"
    - "name"
    properties:
      zip:
        type: "string"
        description: "郵便番号"
      addresss3:
        type: "string"
        description: "住所３"
      address2:
        type: "string"
        description: "住所２"
      phone:
        type: "string"
        description: "代表電話番号"
      address1:
        type: "string"
        description: "住所１"
      pref:
        type: "string"
        description: "都道府県"
      name:
        type: "string"
        description: "会社名称"
      active:
        type: "boolean"
        description: "このデータが現在有効であれば正を設定"
      id:
        type: "string"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）Inputされたidと\
          同じ値となる"
      fax:
        type: "string"
        description: "FAX番号"
  inline_response_200:
    required:
    - "id"
    - "total"
    properties:
      total:
        type: "integer"
        description: "全担当営業数（検索条件に一致した件数）"
      Sales:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_Sales"
      id:
        type: "string"
        description: "会社ID"
  inline_response_200_2:
    required:
    - "email"
    - "total"
    properties:
      total:
        type: "integer"
        format: "int32"
      Companies:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_2_Companies"
      email:
        type: "string"
  inline_response_200_2_Companies:
    required:
    - "id"
    - "name"
    properties:
      name:
        type: "string"
        description: "会社名称"
      id:
        type: "string"
        description: "会社ID（顧客ID）"
  inline_response_200_3:
    required:
    - "companyid"
    - "email"
    - "firstname"
    properties:
      firstname:
        type: "string"
        description: "顧客の名前"
      companyid:
        type: "string"
        description: "会社ID（HANAで管理している会社コード（取引先ID、受注先IDなど）を想定）"
      phone:
        type: "string"
        description: "電話番号"
      mobile:
        type: "string"
        description: "携帯電話番号または緊急連絡先"
      active:
        type: "boolean"
        description: "この顧客データが有効な場合には、正を設定"
      id:
        type: "string"
        description: "顧客ID"
      fax:
        type: "string"
        description: "FAX番号"
      email:
        type: "string"
        description: "Emailアドレス"
      lastname:
        type: "string"
        description: "顧客の苗字"
  inline_response_200_4:
    required:
    - "contract"
    properties:
      note:
        type: "string"
        description: "テキスト（備忘欄？）"
      chargeofenginner:
        type: "string"
        description: "担当技術"
      eol:
        type: "boolean"
        description: "EOL保守の有無"
      contract:
        type: "string"
        description: "個別契約番号"
      customercontractno:
        type: "string"
        description: "顧客契約番号"
      amountof:
        type: "integer"
        description: "契約金額"
      orderby:
        type: "string"
        description: "発注先"
      responsibleparty:
        type: "string"
        description: "顧客担当"
      type:
        type: "string"
        description: "契約種別（ex. 保守）"
      startdate:
        type: "string"
        description: "契約開始日"
      emergencycaller:
        type: "string"
        description: "夜間・休日コール元情報"
      typecode:
        type: "integer"
        description: "契約種別コード"
      caller:
        type: "string"
        description: "コール元会社名"
      enddate:
        type: "string"
        description: "契約終了日"
      fixeddate:
        type: "string"
        description: "契約確定日"
      chargeofsales:
        type: "string"
        description: "担当営業"
      contractid:
        type: "string"
        description: "契約ID"
      typeofconstraction:
        type: "string"
        description: "構築区分"
      id:
        type: "string"
        description: "会社ID"
      automaticrenewal:
        type: "boolean"
        description: "自動更新"
      enteringdate:
        type: "string"
        description: "締結日"
      mastercontract:
        type: "string"
        description: "基本契約番号"
      status:
        type: "string"
        description: "ステータス"
  inline_response_200_Sales:
    required:
    - "email"
    - "salesid"
    properties:
      firstname:
        type: "string"
        description: "担当営業の苗字"
      salesid:
        type: "string"
        description: "担当営業ID（社員番号？）"
      email:
        type: "string"
        description: "担当営業のEmailアドレス"
      lastname:
        type: "string"
        description: "担当営業の名前"
  inline_response_200_7_Product:
    required:
    - "productid"
    properties:
      typeofservice:
        type: "string"
        description: "サービス種別"
      address:
        type: "string"
        description: "住所"
      enddate:
        type: "string"
        description: "契約終了日"
      eol:
        type: "boolean"
        description: "EOL"
      productid:
        type: "string"
        description: "製品ID"
      serial:
        type: "string"
        description: "シリアル番号"
      eos:
        type: "boolean"
        description: "EOS"
      productname:
        type: "string"
        description: "製品テキスト"
      sla:
        type: "string"
        description: "SLA"
      startdate:
        type: "string"
        description: "契約開始日"
