---
swagger: "2.0"
info:
  version: "0.0.8"
  title: "Customer Portal API"
basePath: "/v1"
paths:
  /companies:
    get:
      description: "検索条件に一致した会社情報を提供。検索条件は[ name | id ]"
      operationId: "companiesGET"
      parameters:
      - name: "companyName"
        in: "query"
        description: "会社名称"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスター（顧客または担当営業）のEmailアドレス"
        required: false
        type: "string"
      - name: "rowNumber"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
        format: "int64"
      - name: "currentPage"
        in: "query"
        description: "機器一覧の現在の表示ページ番号"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageLimit"
        in: "query"
        description: "１ページの最大表示行数"
        required: false
        type: "integer"
        format: "int64"
      - name: "searchLimit"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は20最大値は500）"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Companies"
        400:
          description: "Invalid query"
        404:
          description: "Company not found"
      x-swagger-router-controller: "Default"
  /companies/{companyId}:
    get:
      description: "会社IDに従った会社情報を提供"
      operationId: "companiesCompanyIdGET"
      parameters:
      - name: "companyId"
        in: "path"
        description: "会社ID"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Company"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Company not found"
      x-swagger-router-controller: "Default"
  /contracts:
    get:
      description: "保守契約リスト情報を提供"
      operationId: "contractsGET"
      parameters:
      - name: "companyId"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: false
        type: "string"
      - name: "serial"
        in: "query"
        description: "シリアル番号"
        required: false
        type: "string"
      - name: "customerContractNo"
        in: "query"
        description: "顧客契約番号"
        required: false
        type: "string"
      - name: "endUser"
        in: "query"
        description: "エンドユーザー"
        required: false
        type: "string"
      - name: "startDate"
        in: "query"
        description: "契約開始日"
        required: false
        type: "string"
      - name: "endDate"
        in: "query"
        description: "契約終了日"
        required: false
        type: "string"
      - name: "rowNumber"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
        format: "int64"
      - name: "currentPage"
        in: "query"
        description: "機器一覧の現在の表示ページ番号"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageLimit"
        in: "query"
        description: "１ページの最大表示行数"
        required: false
        type: "integer"
        format: "int64"
      - name: "searchLimit"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は20最大値は500）"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Contracts"
        400:
          description: "Invalied query supplied"
        404:
          description: "ContractList not found"
      x-swagger-router-controller: "Default"
  /contracts/{contractId}:
    get:
      description: "保守契約情報を提供"
      operationId: "contractsContractIdGET"
      parameters:
      - name: "contractId"
        in: "path"
        description: "契約番号"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Contract"
        400:
          description: "Invalied ID supplied"
        404:
          description: "Contract not found"
      x-swagger-router-controller: "Default"
  /customers:
    get:
      description: "顧客情報を提供"
      operationId: "customersGET"
      parameters:
      - name: "email"
        in: "query"
        description: "顧客のEmailアドレスを検索キーとして設定"
        required: false
        type: "string"
        format: "string"
      - name: "rowNumber"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
        format: "int64"
      - name: "currentPage"
        in: "query"
        description: "機器一覧の現在の表示ページ番号"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageLimit"
        in: "query"
        description: "１ページの最大表示行数"
        required: false
        type: "integer"
        format: "int64"
      - name: "searchLimit"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は20最大値は500）"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Customers"
        400:
          description: "Invalid query supplied"
        404:
          description: "Customer not found"
      x-swagger-router-controller: "Default"
  /customers/{customerId}:
    get:
      description: "顧客IDに従った顧客情報を提供"
      operationId: "customersCustomerIdGET"
      parameters:
      - name: "customerId"
        in: "path"
        description: "顧客ID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Customer"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Customer not found"
      x-swagger-router-controller: "Default"
  /products:
    get:
      description: "保守契約済み製品リスト情報を提供"
      operationId: "productsGET"
      parameters:
      - name: "companyId"
        in: "query"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "リクエスターのEmailアドレス"
        required: false
        type: "string"
      - name: "customerId"
        in: "query"
        description: "顧客ID"
        required: false
        type: "string"
      - name: "serial"
        in: "query"
        description: "シリアル番号"
        required: false
        type: "string"
      - name: "startDate"
        in: "query"
        description: "契約開始日"
        required: false
        type: "string"
      - name: "endDate"
        in: "query"
        description: "契約終了日"
        required: false
        type: "string"
      - name: "productId"
        in: "query"
        description: "製品ID"
        required: false
        type: "string"
      - name: "productName"
        in: "query"
        description: "製品テキスト"
        required: false
        type: "string"
      - name: "rowNumber"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
        format: "int64"
      - name: "currentPage"
        in: "query"
        description: "機器一覧の現在の表示ページ番号"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageLimit"
        in: "query"
        description: "１ページの最大表示行数"
        required: false
        type: "integer"
        format: "int64"
      - name: "searchLimit"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は20最大値は500）"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Products"
        400:
          description: "Invalied query supplied"
        404:
          description: "ProductList not found"
      x-swagger-router-controller: "Default"
  /products/{productId}:
    get:
      description: "製品IDに従った商品詳細情報を提供"
      operationId: "productsProductIdGET"
      parameters:
      - name: "productId"
        in: "path"
        description: "製品ID"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Product"
        400:
          description: "Invalied ID supplied"
        404:
          description: "Product not found"
      x-swagger-router-controller: "Default"
  /saleses:
    get:
      description: "担当営業情報を提供する"
      operationId: "salesesGET"
      parameters:
      - name: "email"
        in: "query"
        description: "顧客のEmailアドレス（アカウントID）"
        required: false
        type: "string"
      - name: "rowNumber"
        in: "query"
        description: "機器一覧を取得する際の開始位置（最初から取得する場合は0を設定）"
        required: false
        type: "integer"
        format: "int64"
      - name: "currentPage"
        in: "query"
        description: "機器一覧の現在の表示ページ番号"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageLimit"
        in: "query"
        description: "１ページの最大表示行数"
        required: false
        type: "integer"
        format: "int64"
      - name: "searchLimit"
        in: "query"
        description: "最大該当数（最大取得数：デフォルト値は20最大値は500）"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Saleses"
        400:
          description: "Invalied email supplied"
        404:
          description: "Sales not found"
      x-swagger-router-controller: "Default"
  /saleses/{userId}:
    get:
      description: "担当営業情報を提供する"
      operationId: "salesesUserIdGET"
      parameters:
      - name: "userId"
        in: "path"
        description: "社員番号"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Sales"
        400:
          description: "Invalied ID supplied"
        404:
          description: "Sales not found"
      x-swagger-router-controller: "Default"
definitions:
  Customer:
    type: "object"
    required:
    - "companyId"
    - "email"
    - "firstname"
    properties:
      customerId:
        type: "string"
        format: "string"
        description: "顧客ID"
      firstname:
        type: "string"
        format: "string"
        description: "顧客の名前"
      lastname:
        type: "string"
        format: "string"
        description: "顧客の苗字"
      email:
        type: "string"
        format: "string"
        description: "Emailアドレス"
      phone:
        type: "string"
        format: "string"
        description: "電話番号"
      mobile:
        type: "string"
        format: "string"
        description: "携帯電話番号または緊急連絡先番号"
      fax:
        type: "string"
        format: "string"
        description: "FAX番号"
      companyId:
        type: "string"
        format: "string"
        description: "所属会社ID（HANAで管理している会社コード（取引先ID、受注先IDなど）を想定）"
      active:
        type: "boolean"
        description: "この顧客データが有効であれば正を設定（デフォルトは正）"
        default: true
    description: "顧客情報"
  Customers:
    type: "object"
    properties:
      totalEntries:
        type: "integer"
        format: "int64"
      rowNumber:
        type: "integer"
        format: "int64"
      currentPage:
        type: "integer"
        format: "int64"
      pageLimit:
        type: "integer"
        format: "int64"
      Customers:
        type: "array"
        items:
          $ref: "#/definitions/Customer"
    description: "顧客情報リスト"
  Company:
    type: "object"
    required:
    - "companyId"
    - "companyName"
    properties:
      companyId:
        type: "string"
        format: "string"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先IDで使用しているIDを想定）"
      companyName:
        type: "string"
        format: "string"
        description: "会社名称"
      zip:
        type: "string"
        format: "string"
        description: "郵便番号"
      pref:
        type: "string"
        format: "string"
        description: "都道府県"
      address1:
        type: "string"
        format: "string"
        description: "住所１"
      address2:
        type: "string"
        format: "string"
        description: "住所２"
      address3:
        type: "string"
        format: "string"
        description: "住所３"
      phone:
        type: "string"
        format: "string"
        description: "代表電話番号"
      fax:
        type: "string"
        format: "string"
        description: "FAX番号"
      active:
        type: "boolean"
        description: "このデータが現在有効であれば正を設定"
        default: true
    description: "会社情報"
  Companies:
    type: "object"
    required:
    - "email"
    - "rowNumber"
    - "totalEntries"
    properties:
      email:
        type: "string"
      totalEntries:
        type: "integer"
        format: "int64"
      rowNumber:
        type: "integer"
        format: "int64"
      currentPage:
        type: "integer"
        format: "int64"
      pageLimit:
        type: "integer"
        format: "int64"
      Companies:
        type: "array"
        items:
          $ref: "#/definitions/Company"
    description: "会社情報リスト"
  Sales:
    type: "object"
    required:
    - "email"
    - "salesId"
    properties:
      salesId:
        type: "string"
        description: "担当営業ID（社員番号？）"
      email:
        type: "string"
        description: "担当営業のEmailアドレス"
      firstname:
        type: "string"
        description: "担当営業の苗字"
      lastname:
        type: "string"
        description: "担当営業の名前"
    description: "担当営業情報"
  Saleses:
    type: "object"
    properties:
      totalEntries:
        type: "integer"
        format: "int64"
      rowNumber:
        type: "integer"
        format: "int64"
      currentPage:
        type: "integer"
        format: "int64"
      pageLimit:
        type: "integer"
        format: "int64"
      Saleses:
        type: "array"
        items:
          $ref: "#/definitions/Sales"
    description: "担当営業リスト"
  Contract:
    type: "object"
    required:
    - "contract"
    - "contractId"
    properties:
      contractId:
        type: "string"
        description: "契約ID"
      contract:
        type: "string"
        description: "個別契約番号"
      companyId:
        type: "string"
        description: "会社ID"
      typeCode:
        type: "integer"
        description: "契約種別コード"
      type:
        type: "string"
        description: "契約種別（ex. 保守）"
      masterContract:
        type: "string"
        description: "基本契約番号"
      note:
        type: "string"
        description: "テキスト（備忘欄？）"
      orderBy:
        type: "string"
        description: "発注先"
      responsibleParty:
        type: "string"
        description: "顧客担当"
      caller:
        type: "string"
        description: "コール元会社名"
      emergencyCaller:
        type: "string"
        description: "夜間・休日コール元情報"
      chargeOfSales:
        type: "string"
        description: "担当営業"
      chargeOfEnginner:
        type: "string"
        description: "担当技術"
      customerContractNo:
        type: "string"
        description: "顧客契約番号"
      status:
        type: "string"
        description: "ステータス"
      amountOf:
        type: "integer"
        description: "契約金額"
      automaticRenewal:
        type: "boolean"
        description: "自動更新"
      startDate:
        type: "string"
        description: "契約開始日"
      endDate:
        type: "string"
        description: "契約終了日"
      enteringDate:
        type: "string"
        description: "締結日"
      fixedDate:
        type: "string"
        description: "契約確定日"
      eol:
        type: "boolean"
        description: "EOL保守の有無"
      typeOfConstraction:
        type: "string"
        description: "構築区分"
      subject:
        type: "string"
        description: "契約名称"
      endUser:
        type: "string"
        description: "エンドユーザー"
    description: "保守契約情報"
  Contracts:
    type: "object"
    required:
    - "companyId"
    - "rowNumber"
    - "totalEntries"
    properties:
      companyId:
        type: "string"
        description: "会社ID（SAP/HANAで管理している会社コード/取引先ID,受注先ID、納入先コード等で使用しているIDを想定）Inputさ\
          れたidと同じ値となる"
      totalEntries:
        type: "integer"
        description: "検索条件に一致した件数"
      rowNumber:
        type: "integer"
        description: "データの開始位置"
      currentPage:
        type: "integer"
        format: "int64"
        description: "データの提供数"
      pageLimit:
        type: "integer"
        format: "int64"
      Contracts:
        type: "array"
        items:
          $ref: "#/definitions/Contract"
    description: "保守契約リスト"
  Product:
    type: "object"
    required:
    - "contract"
    - "productId"
    properties:
      productId:
        type: "string"
        description: "製品ID"
      productName:
        type: "string"
        description: "製品テキスト"
      contract:
        type: "string"
        description: "個別契約番号"
      modelNo:
        type: "string"
        description: "メーカー型番"
      startDate:
        type: "string"
        description: "保守開始日"
      endDate:
        type: "string"
        description: "保守終了日"
      eos:
        type: "boolean"
        description: "EOS"
      eol:
        type: "boolean"
        description: "EOL"
      individualContract:
        type: "string"
        description: "製品／個別条件書"
      serviceMenu:
        type: "string"
        description: "メニュー名"
      serviceModelNo:
        type: "string"
        description: "サービス型番"
      productListPrice:
        type: "string"
        description: "製品定価"
      serviceTypeCode:
        type: "string"
        description: "サービス種別コード"
      serviceType:
        type: "string"
        description: "サービス種別"
      sla:
        type: "string"
        description: "SLA"
      accountMgmtNo:
        type: "string"
        description: "アカウント管理番号"
      moniteringType:
        type: "string"
        description: "モニタリング種別"
      dedicatedMaintenanceNo:
        type: "string"
        description: "専用保守部材管理番号"
      qa:
        type: "boolean"
        description: "QA有無"
      shippingNo:
        type: "string"
        description: "出荷番号"
      shippingDate:
        type: "string"
        description: "出荷日時"
      serial:
        type: "string"
        description: "シリアル番号"
      typeOfService:
        type: "string"
        description: "サービス種別"
      address:
        type: "string"
        description: "住所"
    description: "製品情報"
  Products:
    type: "object"
    properties:
      totalEntries:
        type: "integer"
        format: "int64"
      rowNumber:
        type: "integer"
        format: "int64"
      currentPage:
        type: "integer"
        format: "int64"
      pageLimit:
        type: "integer"
        format: "int64"
      Products:
        type: "array"
        items:
          $ref: "#/definitions/Product"
    description: "商品情報リスト"
